[workspace]
members = [
    "crates/resolvers/client",
    "crates/resolvers/endpoint",
    "crates/entrypoints/server",
    "crates/entrypoints/entrypoint",
    "crates/lib/expirecollections",
]
resolver = "2"


[profile.release]
opt-level = "z"
lto = "thin"
debug = false
strip = true
