imports_granularity = "Crate"
newline_style="Unix"
reorder_imports = true
reorder_impl_items = true
binop_separator = "Front"
group_imports = "StdExternalCrate"
indent_style = "Block"
hard_tabs = true
imports_indent = "Block"